version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs
    container_name: "ipfs"
    restart: always
    expose:
    - 4001
    - 8080
    ports:
    - 4001:4001
    - 5001:5010
    - 8080:8082 # Gateway 
    volumes:
      - ipfs-data:/data

volumes:
  ipfs-data:
    driver: local