version: '3'
services:
  ipfs:
    image: ipfs/go-ipfs
    container_name: "ipfs"
    restart: always
    expose: # internal links
    - 4001
    - 5001
    - 8080
    ports: # externally available
    - 4001:4001
    - 5010:5001
    # - 8082:8080 # Gateway 
    volumes:
      - ipfs-data:/data

volumes:
  ipfs-data:
    driver: local

networks:
  default:
    driver: bridge